version: '3.7'

services:
  octoprint:
    container_name: octoprint
    image: octoprint/octoprint:1.10.3
    restart: unless-stopped
    networks:
      automation:
        ipv4_address: 192.168.5.140
    devices:
     - /dev/ttyACM0:/dev/ttyACM0
    volumes:
     - ./config/octoprint:/octoprint

  mediamtx:
    image: bluenviron/mediamtx:latest-rpi
    container_name: mediamtx
    privileged: true
    networks:
      automation:
        ipv4_address: 192.168.5.139
    volumes:
      - ./config/mediamtx/mediamtx.yml:/mediamtx.yml
      - /run/udev:/run/udev:ro
    tmpfs:
      - /dev/shm:exec
    restart: unless-stopped
    environment:
      - MTX_PATHS_CAM_SOURCE=rpiCamera

networks:
  automation:
    external: true
